### ISSUE TITLE
Livedemo appears to be nonfunctional

### ISSUE THREAD

**Issue by catskul** [zed0/clang-format-configurator#14]
Javascript console upon upload shows:

```
configurator.js:131 Uncaught TypeError: Cannot read property 'undefined' of undefined
    at configurator.js:131
    at lodash.min.js:26
    at _t (lodash.min.js:14)
    at lodash.min.js:25
    at Function.<anonymous> (lodash.min.js:30)
    at FileReader.reader.onload (configurator.js:130)
(anonymous) @ configurator.js:131
(anonymous) @ lodash.min.js:26
_t @ lodash.min.js:14
(anonymous) @ lodash.min.js:25
(anonymous) @ lodash.min.js:30
reader.onload @ configurator.js:130
FileReader (async)
(anonymous) @ configurator.js:142
(anonymous) @ lodash.min.js:25
(anonymous) @ lodash.min.js:30
load_config @ configurator.js:119
dispatch @ jquery-1.11.3.min.js:4
r.handle @ jquery-1.11.3.min.js:4
```

**Comment by zed0** [comment]
The basic functionality seems to be working for me at the moment.
When you say "upon upload" do you mean if you upload your own configuration?  If so could you send me the configuration?  Which version of clang-format did you make the config for?  I may not have updated recently enough.

**Comment by catskul** [comment]
> When you say "upon upload" do you mean if you upload your own configuration?

Yep

[.clang-format.txt](https://github.com/zed0/clang-format-configurator/files/1744634/default.clang-format.txt)

Also, before hand the left pane is completely blank:

![image](https://user-images.githubusercontent.com/375302/36490306-f9164c30-16f5-11e8-9a0a-e0bc2d7b1727.png)

IIRC there was supposed to be something on the left by default.

Attempting to save with nothing also results in javascript error on the console though perhaps that's expected?:

```
configurator.js:161 Uncaught TypeError: Cannot read property 'undefined' of undefined
    at get_config (configurator.js:161)
    at save_config (configurator.js:148)
    at HTMLButtonElement.<anonymous> (configurator.js:79)
    at HTMLButtonElement.dispatch (jquery-1.11.3.min.js:4)
    at HTMLButtonElement.r.handle (jquery-1.11.3.min.js:4)
get_config @ configurator.js:161
save_config @ configurator.js:148
(anonymous) @ configurator.js:79
dispatch @ jquery-1.11.3.min.js:4
r.handle @ jquery-1.11.3.min.js:4
```

**Comment by zed0** [comment]
Using that .clang-format.txt isn't producing javascript errors for me.  Are there network errors visible in your browser?

**Comment by catskul** [comment]
No visible network errors. All network requests appear to be 200.

Hard reload, and clearing cache for url has no effect.

Problem also exists on firefox, but message is different:

```
TypeError: clang_version is undefined
[Learn More]
configurator.js:131:9
load_config/</reader.onload/<
https://zed0.co.uk/clang-format-configurator/configurator.js:131:9
Zt/<
https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.10.1/lodash.min.js:26:23
_t
https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.10.1/lodash.min.js:14:392
Vt/<
https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.10.1/lodash.min.js:25:369
ur/<
https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.10.1/lodash.min.js:30:73
load_config/</reader.onload
```

**Comment by s-martin** [comment]
On FF 58.0.2 I don't see anything in the left window.
When clicking update I get:

```
TypeError: version is undefined
[Weitere Informationen]
configurator.js:161:2
get_config
https://zed0.co.uk/clang-format-configurator/configurator.js:161:2
request_update
https://zed0.co.uk/clang-format-configurator/configurator.js:91:19
<anonym>
https://zed0.co.uk/clang-format-configurator/configurator.js:76:3
dispatch
https://code.jquery.com/jquery-1.11.3.min.js:4:8497
add/r.handle
https://code.jquery.com/jquery-1.11.3.min.js:4:5235
```

IE11 seems also not to work

**Comment by zed0** [comment]
Can you confirm that it is actually making a request to `https://zed0.co.uk:2001/doc`?

**Comment by s-martin** [comment]
When I tried to open that URL in FF, I got a message that my (corporate) proxy blocked that request.

I assume it's because of the unusal port (`2001`).

**Comment by zed0** [comment]
That will be the issue.  I'll have a look at making some modifications so that it can all be served through 443.  I'm fairly pressed for time though so it might take me some time.

**Comment by catskul** [comment]
For me it just hangs while connecting, but may be a similar issue.

**Comment by cengiz-io** [comment]
@zed0 Please renew Let's Encrypt certificate.

> zed0.co.uk:2001 uses an invalid security certificate. 
The certificate expired on June 7, 2018, 11:34:52 AM GMT+3. 
The current time is June 9, 2018, 12:21 AM. 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by zed0** [comment]
@cengizIO thanks, I've just fixed that.  Could have sworn I did that a few days ago.
In future please create a separate issue, thanks.

**Comment by s-martin** [comment]
Just asking, if there are any updates on using a more standard port?

**Comment by zed0** [comment]
Everything should now be served on the default https port.  Let me know if you have any more difficulties.

**Comment by s-martin** [comment]
Just confirmed it works behind my corporate proxy.

Thanks!
