### ISSUE TITLE
Add clang-format 7

### ISSUE THREAD

**Issue by patrickelectric** [zed0/clang-format-configurator#18]
clang-format 7.0.0 is already available.

**Comment by asmaloney** [comment]
...and I now have 8.0.0 via homebrew on macOS :-)

`clang-format version 8.0.0 (tags/google/stable/2018-12-18)`

**Comment by hartwork** [comment]
Upstream is at version 10 by now. Any news?

**Comment by zed0** [comment]
I've updated the setup script and added the more recent versions.  Some of the features still don't work (e.g. the custom bracketing options), but hopefully it's useful anyway.

**Comment by hartwork** [comment]
I'd try it but I get error 503 at https://zed0.co.uk/clang-format-configurator/ right now.

**Comment by zed0** [comment]
Apologies, up again.

**Comment by hartwork** [comment]
Cool, thank you!
