### ISSUE TITLE
Website down (503)

### ISSUE THREAD

**Issue by SimonLammer** [zed0/clang-format-configurator#19]
A request to [https://zed0.co.uk/clang-format-configurator/](https://zed0.co.uk/clang-format-configurator/) results in a 503 error.
> Service Unavailable
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
> Apache/2.4.18 (Ubuntu) Server at zed0.co.uk Port 443

**Comment by zed0** [comment]
Sorry about that, should be up again.
