### ISSUE TITLE
Ability to upload clang-format

### ISSUE THREAD

**Issue by quicknir** [zed0/clang-format-configurator#6]
This may seem like an odd request, but it would actually be tremendously useful. For instance, if you want to share an existing clang-format file with coworkers, and they do not yet have it integrated into their workflow, this would be a very easy way to show them what style you are proposing and to allow them to iterate on it. But currently it would be necessary to manually set the fields one at a time to match the text file.

**Comment by zed0** [comment]
I like this idea, what sort of sharing would you suggest?  Do you want to be able to upload a .clang-format file or would you rather be able to copy a permalink to a specific configuration?

**Comment by szechyjs** [comment]
I would like to be able to upload a .clang-format so that I can make changes to it without having to populate each field based on the file.

**Comment by quicknir** [comment]
I actually think uploading a file is the easiest. An alternative is to use github gists, as they're easy to create; you could just copy and paste the entire file into the github gist and then paste the link into your site. That's fine for me, but for some people it may be an annoyance if they don't have github accounts.
